on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup linter  
      run: dotnet tool install -g dotnet-fsharplint
    - name: Setup formatter
      run: dotnet tool install -g fantomas
    - name: Restore dependencies
      run: dotnet restore src/src.fsproj
      
    - name: Build
      run: dotnet build ./src
    - name: Lint 
      run: dotnet-fsharplint lint ./src
    - name: Format 
      run: fantomas ./src/*.fs

    - name: Run
      run: dotnet run --project ./src

    - name: Test
      run: |
          dotnet restore tests/tests.fsproj
          dotnet build ./tests
          dotnet test ./tests
